skip PathManager stuff for NFS save
It seems to cause problems:

line 254, in <lambda>
    self._notify_manager(lambda: self._io.write(b))
OSError: [Errno 14] Bad address

But it isn't even needed for saving while also doing training.