skip PathManager stuff for NFS save  (#497)
* Revert "Split to multiple sbatch copy jobs (#502)"

This reverts commit ae980c13e04b910d1d61bdd680e60a7c3bef8d4e.

* Revert "Launch separate sbatch job to copy checkpoints over from scratch to NFS (#494)"

This reverts commit 364d7315dfe91046fb1b58450edeac67e7d83a10.

* skip PathManager stuff for NFS save

It seems to cause problems:

line 254, in <lambda>
    self._notify_manager(lambda: self._io.write(b))
OSError: [Errno 14] Bad address

But it isn't even needed for saving while also doing training. Instead we launch a separate thread that calls cp, and use some logic in the loading pathway to find the last finished checkpoint.